server:
  port: 8081

spring:
  application:
    name: ProductService

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    host: host.docker.internal
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
