server:
  port: 8765

spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://CUSTOMERSERVICE
              predicates:
                - Path=/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
