server:
  port: 8084

spring:
  application:
    name: NotificationService

  kafka:
    bootstrap-servers: localhost:9092
    new-order-topic-name: ordertrack.neworder
    new-order-group-id: ordertrack.orderuser.group
    value-default-type: by.kabral.ordertrack.dto.ProcessedOrderDto
    trusted-packages: by.kabral.ordertrack.*
    partitions-count: 1

  mail:
    host: localhost
    port: 1025
    username: no-reply@ordertrack.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true