server:
  port: 8083

spring:
  application:
    name: OrderService

  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      uuid-representation: standard

    redis:
      host: host.docker.internal
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

client:
  product-service-uri: http://localhost:8765/products

